CREATE DATABASE AMAZON;
USE AMAZON;

CREATE TABLE amazon_raw (
    order_id VARCHAR(50),
    order_date DATE,
    customer_id VARCHAR(50),
    customer_name VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),
    seller_id VARCHAR(50),
    product_id VARCHAR(50),
    product_name VARCHAR(255),
    category VARCHAR(100),
    brand VARCHAR(100),
    quantity INT,
    unit_price DECIMAL(10,2),
    discount DECIMAL(10,2),
    tax DECIMAL(10,2),
    shipping_cost DECIMAL(10,2),
    payment_method VARCHAR(50),
    order_status VARCHAR(50),
    total_amount DECIMAL(10,2)
);

DESCRIBE amazon_raw;

SELECT * FROM AMAZON_RAW;

SELECT CUSTOMER_NAME FROM AMAZON_RAW;

SELECT PRODUCT_NAME,UNIT_PRICE
FROM AMAZON_RAW;

SELECT DISTINCT CATEGORY
FROM AMAZON_RAW;

SELECT COUNT(ORDER_ID) AS TOTAL_ORDER
FROM AMAZON_RAW;

SELECT COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMER
FROM AMAZON_RAW;

SELECT COUNT(PRODUCT_ID) AS TOTAL_PRODUCT
FROM AMAZON_RAW;

SELECT PRODUCT_NAME,PRODUCT_ID,UNIT_PRICE FROM AMAZON_RAW
WHERE UNIT_PRICE = (SELECT MAX( UNIT_PRICE) FROM AMAZON_RAW);

SELECT PRODUCT_ID,PRODUCT_NAME, UNIT_PRICE
FROM AMAZON_RAW WHERE UNIT_PRICE = (SELECT MIN(UNIT_PRICE) FROM AMAZON_RAW);

SELECT ROUND(AVG(UNIT_PRICE)) AS average_product
FROM AMAZON_RAW;

SELECT SUM(QUANTITY*UNIT_PRICE) AS TOTAL_SALES
FROM AMAZON_RAW;

SELECT SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM AMAZON_RAW;

SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    UNIT_PRICE
FROM AMAZON_RAW
WHERE UNIT_PRICE > 1000;

SELECT *
FROM AMAZON_RAW 
WHERE ORDER_STATUS = 'CANCELLED';

SELECT *
FROM AMAZON_RAW 
WHERE ORDER_STATUS = 'DELIVERED';

SELECT PRODUCT_NAME,CATEGORY
FROM AMAZON_RAW
WHERE CATEGORY = 'ELECTRONICS';

SELECT PRODUCT_ID,PRODUCT_NAME,UNIT_PRICE
FROM AMAZON_RAW
ORDER BY UNIT_PRICE DESC;

SELECT PRODUCT_ID,PRODUCT_NAME,UNIT_PRICE
FROM AMAZON_RAW
ORDER BY UNIT_PRICE ASC;

SELECT * FROM AMAZON_RAW
LIMIT 10;

SELECT * FROM AMAZON_RAW
WHERE ORDER_DATE > '2024-01-01';

SELECT SUM(QUANTITY*UNIT_PRICE) AS TOTAL_SALES,
		CATEGORY 
FROM AMAZON_RAW
GROUP BY CATEGORY;

SELECT BRAND,
	SUM(QUANTITY*UNIT_PRICE) AS TOTAL_SALES
FROM AMAZON_RAW
GROUP BY BRAND;

SELECT CUSTOMER_ID,
	ROUND(SUM(QUANTITY*UNIT_PRICE))AS TOTAL_SALES
FROM AMAZON_RAW
GROUP BY CUSTOMER_ID;

WITH CTE AS (
	SELECT 
		CUSTOMER_ID,CUSTOMER_NAME,
        SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
	FROM AMAZON_RAW
    GROUP BY CUSTOMER_ID,CUSTOMER_NAME
)
SELECT 
	CUSTOMER_ID,CUSTOMER_NAME,
    TOTAL_REVENUE
FROM (
	SELECT *,
    DENSE_RANK() OVER (ORDER BY TOTAL_REVENUE DESC) AS RNK
FROM CTE) AS RANKED
WHERE RNK <= 10;


WITH REVENUE AS (
	SELECT PRODUCT_ID,PRODUCT_NAME,
    SUM(TOTAL_AMOUNT) AS TOTAL
FROM AMAZON_RAW
GROUP BY PRODUCT_ID,PRODUCT_NAME
)
SELECT PRODUCT_ID,PRODUCT_NAME,
	TOTAL
FROM (
	SELECT *,
    DENSE_RANK() OVER (ORDER BY TOTAL DESC) AS PR
FROM REVENUE) AS T
WHERE PR<=10;

WITH BRAND_REVENUE AS (
	SELECT BRAND,
    SUM(TOTAL_AMOUNT) AS REVENUE
FROM AMAZON_RAW
GROUP BY BRAND
)
SELECT BRAND,REVENUE
FROM (
SELECT *,
	ROW_NUMBER() OVER (ORDER BY REVENUE DESC) AS BR
FROM BRAND_REVENUE) AS B
WHERE BR <=5;

WITH ORDER_TOTAL AS (
SELECT ORDER_ID,
	SUM(QUANTITY*UNIT_PRICE) AS TOTAL
FROM AMAZON_RAW
GROUP BY ORDER_ID
)
SELECT AVG(TOTAL) AS AVERAGE_ORDER_VALUE FROM ORDER_TOTAL ;

WITH QUANTITY_TOTAL AS (
SELECT ORDER_ID,
	SUM(QUANTITY) AS TOTAL
FROM AMAZON_RAW
GROUP BY ORDER_ID
)
SELECT ROUND(AVG(TOTAL)) AS AVERAGE_QUANTITY FROM QUANTITY_TOTAL;

SELECT PAYMENT_METHOD,
	COUNT(*) AS TOTAL
FROM AMAZON_RAW
GROUP BY PAYMENT_METHOD
ORDER BY TOTAL DESC;

SELECT ORDER_STATUS,
	COUNT(*) AS TOTAL_COUNT
FROM AMAZON_RAW
GROUP BY ORDER_STATUS;


SELECT DATE_FORMAT(ORDER_DATE,'%Y-%M')AS MONTHLY,
	ROUND(SUM(QUANTITY*UNIT_PRICE)) AS TOTAL
FROM AMAZON_RAW
GROUP BY DATE_FORMAT(ORDER_DATE,'%Y-%M')
ORDER BY MONTHLY ASC;

SELECT YEAR(ORDER_DATE) AS YEARLY,
	ROUND(SUM(QUANTITY*UNIT_PRICE)) AS TOTAL
FROM AMAZON_RAW
GROUP BY YEAR(ORDER_DATE)
ORDER BY YEARLY;


SELECT CITY,
	SUM(QUANTITY*UNIT_PRICE) AS CITY_REVENUE
FROM AMAZON_RAW
GROUP BY CITY;

SELECT COUNTRY,
	SUM(QUANTITY*UNIT_PRICE) AS COUNTRY_REVENUE
FROM AMAZON_RAW
GROUP BY COUNTRY;

SELECT STATE,
	SUM(QUANTITY*UNIT_PRICE) AS STATE_REVENUE
FROM AMAZON_RAW
GROUP BY STATE;

WITH HIGHEST AS (
	SELECT CATEGORY ,
		SUM(QUANTITY*UNIT_PRICE) AS TOTAL
FROM AMAZON_RAW
GROUP BY CATEGORY )
SELECT  CATEGORY ,
	TOTAL
FROM(
SELECT *,
	DENSE_RANK() OVER (ORDER BY TOTAL DESC) AS RNK
FROM HIGHEST) AS RANKED
WHERE RNK =1;

WITH LOWEST AS (
	SELECT CATEGORY ,
		SUM(QUANTITY) AS TOTAL
FROM AMAZON_RAW
GROUP BY CATEGORY )
SELECT  CATEGORY ,
	TOTAL
FROM(
SELECT *,
	DENSE_RANK() OVER (ORDER BY TOTAL ASC) AS RNK
FROM LOWEST) AS RANKED
WHERE RNK =1;

WITH CTE AS (
	SELECT CATEGORY ,
    SUM(TOTAL_AMOUNT) AS TOTAL
FROM AMAZON_RAW
GROUP BY CATEGORY
)
SELECT CATEGORY,
	TOTAL
FROM (
	SELECT *,
	RANK() OVER ( ORDER BY TOTAL DESC) AS RNK
FROM CTE)T
WHERE RNK =1;

SELECT 
	CUSTOMER_ID,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER
FROM AMAZON_RAW
GROUP BY CUSTOMER_ID 
HAVING COUNT(DISTINCT ORDER_ID) = 1;

SELECT CUSTOMER_ID,
	COUNT(*) AS TOTAL
FROM AMAZON_RAW
GROUP BY CUSTOMER_ID
HAVING COUNT(*)>1;

WITH CUSTOMER_ORDER AS (
	SELECT CUSTOMER_ID,
    COUNT(*) AS TOTAL_ORDER
FROM AMAZON_RAW
GROUP BY CUSTOMER_ID
)
SELECT *
FROM CUSTOMER_ORDER
WHERE TOTAL_ORDER >5
ORDER BY TOTAL_ORDER DESC;

SELECT 
	ROUND(SUM(TAX)) AS TOTAL_TAX
FROM AMAZON_RAW;

SELECT CATEGORY,
    AVG(DISCOUNT) AS AVG_DIS
FROM AMAZON_RAW
GROUP BY CATEGORY
ORDER BY AVG_DIS;

SELECT SUM(TAX) AS TOTAL_TAX
FROM AMAZON_RAW;

SELECT ROUND(AVG(SHIPPING_COST)) AS AVG_SHPPING
FROM AMAZON_RAW;

WITH HIGH_COST AS (
	SELECT ORDER_ID,
		PRODUCT_NAME,
        SHIPPING_COST,
        DENSE_RANK() OVER (ORDER BY SHIPPING_COST DESC) AS RNK
FROM AMAZON_RAW)
SELECT ORDER_ID,
		PRODUCT_NAME,
        SHIPPING_COST
FROM HIGH_COST
WHERE RNK =1;


WITH LOWEST_COST AS (
	SELECT ORDER_ID,
		PRODUCT_NAME,
        SHIPPING_COST,
        DENSE_RANK() OVER (ORDER BY SHIPPING_COST ASC) AS RNK
FROM AMAZON_RAW)
SELECT ORDER_ID,
		PRODUCT_NAME,
        SHIPPING_COST
FROM LOWEST_COST
WHERE RNK =1;

WITH CTE AS (
	SELECT CATEGORY,
		PRODUCT_NAME,
        SUM(QUANTITY * UNIT_PRICE) AS TOTAL
FROM AMAZON_RAW
GROUP BY CATEGORY,PRODUCT_NAME
)
SELECT *
FROM (
	SELECT *,
		DENSE_RANK() OVER (PARTITION BY CATEGORY ORDER BY TOTAL DESC) AS RNK
	FROM CTE )T 
WHERE RNK <=3;

SELECT PRODUCT_NAME,
		TOTAL
FROM 
(SELECT PRODUCT_NAME,
	 SUM(QUANTITY*UNIT_PRICE) AS TOTAL,
     DENSE_RANK() OVER (ORDER BY SUM(QUANTITY*UNIT_PRICE) DESC ) AS RNK
FROM AMAZON_RAW
GROUP BY PRODUCT_NAME)T
WHERE RNK =2;

SELECT CUSTOMER_ID, CUSTOMER_NAME,
	TOTAL_REVENUE
FROM (
SELECT CUSTOMER_ID, CUSTOMER_NAME,
	SUM(QUANTITY*UNIT_PRICE) AS TOTAL_REVENUE,
    DENSE_RANK() OVER (ORDER BY SUM(QUANTITY*UNIT_PRICE) DESC) AS RNK
FROM AMAZON_RAW
GROUP BY CUSTOMER_ID,CUSTOMER_NAME)R
WHERE RNK =3;


SELECT CUSTOMER_ID,CUSTOMER_NAME,
	SUM(QUANTITY*UNIT_PRICE) AS TOTAL,
    RANK() OVER (ORDER BY SUM(QUANTITY*UNIT_PRICE) DESC) AS RNK
FROM AMAZON_RAW
GROUP BY CUSTOMER_ID,CUSTOMER_NAME;


WITH CTE AS(
		SELECT PRODUCT_NAME,
        SUM(QUANTITY*UNIT_PRICE) AS TOTAL
FROM AMAZON_RAW
GROUP BY PRODUCT_NAME
)
SELECT *,
	DENSE_RANK() OVER (ORDER BY TOTAL DESC) 
FROM CTE ;

WITH DAILY_SALES AS(
	SELECT ORDER_DATE,
		SUM(QUANTITY*UNIT_PRICE) AS DAILY_TOTAL
	FROM AMAZON_RAW
    GROUP BY ORDER_DATE
    )
    SELECT ORDER_DATE,
			DAILY_TOTAL,
            SUM(DAILY_TOTAL) OVER (ORDER BY ORDER_DATE ) AS RUNNING_TOTAL
	FROM DAILY_SALES;

WITH MONTHLY AS(
	SELECT DATE_FORMAT(ORDER_DATE,'%Y-%M') AS MON,
    SUM(QUANTITY * UNIT_PRICE) AS SALES
FROM AMAZON_RAW
GROUP BY DATE_FORMAT(ORDER_DATE,'%Y-%M')
)
SELECT *,
SUM(SALES) OVER (ORDER BY MON) AS CUMULATIVE_REVENUE
FROM MONTHLY;


WITH MONTHLY AS(
	SELECT 
    DATE_FORMAT(ORDER_DATE,'%Y-%M') AS MON,
    SUM(QUANTITY * UNIT_PRICE) AS TOTAL
FROM AMAZON_RAW
GROUP BY DATE_FORMAT(ORDER_DATE,'%Y-%M')
)
SELECT *,
	ROUND(AVG(TOTAL) OVER ( ORDER BY MON 
    ROWS BETWEEN 2 PRECEDING  AND CURRENT ROW),2) ROLLING_AVG
    FROM MONTHLY;


WITH MON AS (
	SELECT DATE_FORMAT(ORDER_DATE,'%Y-%M') AS MONTHLY,
    SUM(QUANTITY*UNIT_PRICE) AS TOTAL
FROM AMAZON_RAW
GROUP BY DATE_FORMAT(ORDER_DATE,'%Y-%M')
)
SELECT 
LAG(TOTAL) OVER (ORDER BY MONTHLY) AS PREVIOUS_MONTH
FROM MON;

SELECT ORDER_ID, ORDER_DATE,
		TOTAL_AMOUNT,
    LAG(TOTAL_AMOUNT) OVER (ORDER BY ORDER_DATE) AS PREVIOUS_ORDER
FROM AMAZON_RAW;

SELECT * FROM(
	SELECT *,
		ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS RNK
FROM AMAZON_RAW)T
WHERE RNK=1;

SELECT *
FROM(
	SELECT *,
    ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE DESC) AS RNK
FROM AMAZON_RAW)T
WHERE RNK=1;

SELECT CUSTOMER_ID
FROM AMAZON_RAW
GROUP BY CUSTOMER_ID
HAVING COUNT(DISTINCT ORDER_ID)=1;

SELECT CUSTOMER_ID
FROM AMAZON_RAW
GROUP BY CUSTOMER_ID
HAVING COUNT(DISTINCT ORDER_ID)>1;

SELECT 
A.PRODUCT_NAME PRODUCT_1,
B.PRODUCT_NAME PRODUCT_2,
COUNT(*) BOUGHT
FROM AMAZON_RAW A 
JOIN AMAZON_RAW B
ON A.ORDER_ID = B.ORDER_ID
AND A.PRODUCT_ID < B.PRODUCT_ID
GROUP BY 
A.PRODUCT_NAME,
B.PRODUCT_NAME
ORDER BY BOUGHT DESC;


WITH CTE AS(
	SELECT PAYMENT_METHOD,
    COUNT(*) AS TOTAL
FROM AMAZON_RAW
GROUP BY PAYMENT_METHOD
)
SELECT *
FROM (
SELECT *,
	DENSE_RANK() OVER (ORDER BY TOTAL DESC) AS RNK
FROM CTE)T
WHERE RNK =1;


WITH CATE_SALE AS (
	SELECT CATEGORY,
		ROUND(AVG(TOTAL_AMOUNT)) AS  AVG_TOTAL
FROM AMAZON_RAW
GROUP BY CATEGORY
)
SELECT *
FROM(
SELECT *,
	RANK() OVER (ORDER BY AVG_TOTAL DESC) AS RNK
FROM CATE_SALE)T
WHERE RNK =1;

SELECT CUSTOMER_ID,
CUSTOMER_NAME,
	SUM(TOTAL_AMOUNT) AS TOTAL_VALUE
FROM AMAZON_RAW
GROUP BY CUSTOMER_ID,CUSTOMER_NAME
ORDER BY TOTAL_VALUE;



SELECT CATEGORY ,
SUM(TOTAL_AMOUNT) AS SALES,
ROUND(SUM(TOTAL_AMOUNT)*100/	
(SELECT SUM(TOTAL_AMOUNT) FROM AMAZON_RAW),2) AS PERCENTAGE
FROM AMAZON_RAW
GROUP BY CATEGORY;

WITH CUSTOMER_SALES AS (
SELECT CUSTOMER_ID ,
	CUSTOMER_NAME,
		SUM(QUANTITY*UNIT_PRICE) AS TOTAL
	FROM AMAZON_RAW
	GROUP BY CUSTOMER_ID,CUSTOMER_NAME
)
SELECT *
FROM (
SELECT *,
	NTILE(5) OVER (ORDER BY TOTAL DESC) AS RNK
FROM CUSTOMER_SALES)T
WHERE RNK =1;


SELECT PRODUCT_ID,PRODUCT_NAME
UNIT_PRICE
FROM AMAZON_RAW
WHERE UNIT_PRICE > 
(SELECT AVG(UNIT_PRICE) FROM AMAZON_RAW);

WITH CUSTOMER_SALES AS(
	SELECT CUSTOMER_ID,
		CUSTOMER_NAME, 
        SUM(TOTAL_AMOUNT) AS TOTAL
FROM AMAZON_RAW
GROUP BY CUSTOMER_ID,CUSTOMER_NAME
)
SELECT *
FROM CUSTOMER_SALES
WHERE TOTAL >
(SELECT AVG(TOTAL)
FROM CUSTOMER_SALES );
        
SELECT *
FROM AMAZON_RAW A
WHERE UNIT_PRICE<
(
SELECT AVG(UNIT_PRICE)
FROM AMAZON_RAW B
WHERE A.CATEGORY=B.CATEGORY);

WITH PRO_CAT AS (
	SELECT PRODUCT_NAME,
		CATEGORY ,
        UNIT_PRICE,
	DENSE_RANK() OVER (PARTITION BY CATEGORY ORDER BY UNIT_PRICE DESC) AS RNK
FROM AMAZON_RAW )
SELECT * FROM PRO_CAT
WHERE RNK=1;


WITH PRO_LOW AS (
	SELECT 	PRODUCT_NAME,
		CATEGORY ,
        UNIT_PRICE
	FROM AMAZON_RAW 
)
SELECT *
FROM (
SELECT *,
	DENSE_RANK() OVER (PARTITION BY CATEGORY ORDER BY UNIT_PRICE ASC) AS RNK
FROM PRO_LOW)T
WHERE RNK=1;

WITH TOTAL AS(
	SELECT CUSTOMER_ID,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER
    FROM AMAZON_RAW
    GROUP BY CUSTOMER_ID
)
SELECT * FROM 
TOTAL;

WITH AVG_VALUE AS (
	SELECT CUSTOMER_ID,
    AVG(TOTAL_AMOUNT) AS AVG_ORDER
FROM AMAZON_RAW
GROUP BY CUSTOMER_ID
)
SELECT * FROM
AVG_VALUE;


WITH HIGH AS (
	SELECT CUSTOMER_ID,
    SUM(TOTAL_AMOUNT) AS TOTAL
FROM AMAZON_RAW
GROUP BY CUSTOMER_ID
)
SELECT *
FROM(
SELECT *,
	DENSE_RANK() OVER (ORDER BY TOTAL DESC) AS RNK
FROM HIGH )T
WHERE RNK=1;

SELECT 
	DATE_FORMAT(ORDER_DATE,'%Y-%m') AS MONTLY,
    SUM(QUANTITY*UNIT_PRICE) AS TOTAL
FROM AMAZON_RAW
GROUP BY DATE_FORMAT(ORDER_DATE,'%Y-%m')
ORDER BY MONTLY;

SELECT ORDER_DATE,
	SUM(TOTAL_AMOUNT) AS TOTAL
FROM AMAZON_RAW
GROUP BY ORDER_DATE
ORDER BY ORDER_DATE;

SELECT 
DAYNAME(ORDER_DATE)	WEEKDAY,
SUM(TOTAL_AMOUNT) AS TOTAL
FROM AMAZON_RAW
WHERE DAYNAME(ORDER_DATE) BETWEEN 0 AND 4
GROUP BY  DAYNAME(ORDER_DATE);

SELECT 
CASE
	WHEN WEEKDAY(ORDER_DATE) IN (5,6)
	THEN 'WEEKEND'
	ELSE 'WEEKDAY'
END DAY_TYPE,
SUM(TOTAL_AMOUNT) AS SALES
FROM AMAZON_RAW
GROUP BY DAY_TYPE;

WITH CTE AS(
	SELECT DATE_FORMAT (ORDER_DATE,'%Y-%M') AS MONTHLY,
    SUM(QUANTITY*UNIT_PRICE) AS TOTAL
FROM AMAZON_RAW
GROUP BY DATE_FORMAT(ORDER_DATE,'%Y-%M')
)
SELECT *
FROM(
SELECT *,
	DENSE_RANK() OVER (ORDER BY TOTAL DESC) AS RNK
FROM CTE )T
WHERE RNK=1;    

SELECT 
	PRODUCT_NAME,
    AVG(QUANTITY) AS AVG_QTY
FROM AMAZON_RAW
GROUP BY PRODUCT_NAME;

WITH HIGH_QTY AS(
	SELECT 
	PRODUCT_NAME,
    AVG(QUANTITY) AS AVG_QTY
FROM AMAZON_RAW
GROUP BY PRODUCT_NAME
)
SELECT *
FROM(
SELECT *,
	DENSE_RANK() OVER (ORDER BY AVG_QTY DESC) AS RNK
FROM HIGH_QTY)T
WHERE RNK=1;

WITH LOW_QTY AS(
	SELECT 
	PRODUCT_NAME,
    AVG(QUANTITY) AS AVG_QTY
FROM AMAZON_RAW
GROUP BY PRODUCT_NAME
)
SELECT *
FROM(
SELECT *,
	DENSE_RANK() OVER (ORDER BY AVG_QTY ASC) AS RNK
FROM LOW_QTY)T
WHERE RNK=1;

SELECT 
	CATEGORY,
     ROUND(AVG(TOTAL_AMOUNT)) AS  AVG_CAT
FROM AMAZON_RAW
GROUP BY CATEGORY;


WITH AVG_CAT AS(
	SELECT 
	CATEGORY,
     SUM(TOTAL_AMOUNT) AS TOTAL
FROM AMAZON_RAW
GROUP BY CATEGORY
)
SELECT * FROM AVG_CAT 
WHERE TOTAL >
(SELECT AVG(TOTAL)
FROM AVG_CAT
);

SELECT CUSTOMER_ID
FROM AMAZON_RAW
GROUP BY CUSTOMER_ID
HAVING COUNT(DISTINCT DATE_FORMAT(ORDER_DATE,'%Y-%M'))>1;

WITH P_REVENUE AS(
	SELECT PRODUCT_NAME,
    SUM(QUANTITY*UNIT_PRICE) AS TOTAL
FROM AMAZON_RAW
GROUP BY PRODUCT_NAME
)
SELECT *
FROM (
SELECT *,
	DENSE_RANK() OVER (ORDER BY TOTAL DESC) AS RNK
FROM P_REVENUE)T
WHERE RNK=1;

WITH LOW_R AS(
	SELECT PRODUCT_NAME,
    SUM(QUANTITY*UNIT_PRICE) AS TOTAL
FROM AMAZON_RAW
GROUP BY PRODUCT_NAME
)
SELECT *
FROM (
SELECT *,
	DENSE_RANK() OVER (ORDER BY TOTAL ASC) AS RNK
FROM LOW_R)T
WHERE RNK=1;

SELECT ORDER_ID,
	COUNT(DISTINCT PRODUCT_ID) AS T_P
FROM AMAZON_RAW
GROUP BY ORDER_ID
HAVING COUNT(DISTINCT PRODUCT_ID)>3;

WITH AVG_P AS (
	SELECT ORDER_ID,
    COUNT(DISTINCT PRODUCT_ID) AS TOTAL_P
FROM AMAZON_RAW
GROUP BY ORDER_ID
)
SELECT 
	AVG(TOTAL_P) AS AVG_PRODUCT FROM AVG_P;
    

SELECT CATEGORY,
		SUM(TOTAL_AMOUNT) AS TOTAL,
	RANK() OVER (ORDER BY SUM(TOTAL_AMOUNT) DESC) AS CATEGORY_RANK
FROM AMAZON_RAW
GROUP BY CATEGORY ;

WITH MONTHLY_SALES AS (
SELECT 
	DATE_FORMAT(ORDER_DATE,'%Y-%M') AS MONTHLY,
    SUM(QUANTITY*UNIT_PRICE) AS TOTAL
FROM AMAZON_RAW
GROUP BY DATE_FORMAT(ORDER_DATE,'%Y-%M')
)
SELECT MONTHLY,
	TOTAL,
    SUM(TOTAL) OVER (ORDER BY MONTHLY) AS RUNNING_TOTAL
FROM MONTHLY_SALES;

WITH MONTHLY AS(
	SELECT 
    DATE_FORMAT(ORDER_DATE,'%Y-%M') AS MON,
    SUM(TOTAL_AMOUNT) AS TOTAL
FROM AMAZON_RAW
GROUP BY DATE_FORMAT(ORDER_DATE,'%Y-%M')
)
SELECT MON,
	TOTAL,
    LAG(TOTAL) OVER (ORDER BY MON) AS PERVIOUS_MONTH
    FROM MONTHLY ;
    

WITH MONTHLY AS(
	SELECT 
    DATE_FORMAT(ORDER_DATE,'%Y-%M') AS MON,
    SUM(TOTAL_AMOUNT) AS TOTAL
FROM AMAZON_RAW
GROUP BY DATE_FORMAT(ORDER_DATE,'%Y-%M')
)
SELECT MON,
	TOTAL,
    LEAD(TOTAL) OVER (ORDER BY MON) AS NEXT_MONTH
    FROM MONTHLY ;
    
WITH CTE AS (
	SELECT 
    DATE_FORMAT(ORDER_DATE,'%Y-%M') AS MON,
    SUM(TOTAL_AMOUNT) AS TOTAL
FROM AMAZON_RAW
GROUP BY DATE_FORMAT(ORDER_DATE,'%Y-%M')
)
SELECT MON,
TOTAL,
    LAG(TOTAL) OVER (ORDER BY MON) AS PERVIOUS_MONTH,
    ((TOTAL-LAG(TOTAL) OVER (ORDER BY MON))
    /
    LAG(TOTAL) OVER (ORDER BY MON)*100
    ) AS GROWTH
FROM CTE;